### ISSUE TITLE
'ㅄ' 받침 뒤에 'ㅇ'이 아닌 글자가 오는 경우 ipa 변환 오류

### ISSUE THREAD

**Issue by Reirusia** [stannam/hangul_to_ipa#11]
'ㅄ' 받침 뒤에 'ㅇ'이 아닌 글자가 오는 경우 오류가 발생하는 것으로 보입니다.
'없다', '없는' 등을 테스트 중 발생했습니다.
'없이', '없음' 등의 단어는 정상 동작하는걸로 확인해서 위와 같이 추측했습니다.
예시로 '없는'을 들자면, 해당 단어의 자모의 변화가 다음과 같았습니다.
'ㅓㅂㅅㄴㅡㄴ'
'ㅓㅁㄴㄴㅡㄴ'
simplify_coda의 simplify에서  double_coda가 'ㅁㄴ'이라 double_coda table에 없어 CT_double_codas.apply가 정상적으로 수행되지 못한 것으로 보이는데, 시간이 없어 자세히 살피지는 못했습니다.
감사합니다.

**Comment by stannam** [comment]
앗 알려주셔서 감사합니다. 빨리 고치도록 하겠습니다!

**Comment by stannam** [comment]
cf. #6
